version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rickymorty
      POSTGRES_USER: rickymorty
      POSTGRES_PASSWORD: rickymorty
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      
  frontend:
    build: ./frontend/rick-and-morty-app
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build: ./backend    
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: unless-stopped
